### ISSUE TITLE
QMC5883 library to Attiny85

### ISSUE THREAD

**Issue by Ulissesp** [mprograms/QMC5883LCompass#1]
Since the wire.h library dont work with Attiny85, we need to use TinyWireM lib.
What do I need to change at QMC5883 library to wok with Attiny85?
Could you help me?
Thank you.

**Comment by mprograms** [comment]
QMC5883L Compass Library uses wire.h for its I2C communications. As you noted, the ATTiny85 does not have this support. I am not 100% familiar with the inner workings of the TinyWireM Library nor do I have a ATTiny85 laying around to test. However, if the functions of Wire and TinyWireM are the same, you might only have to do a quick refactoring of Wire.functionName() to TinyWireM.functionName(). Everything else is related to the QMC5883 chipset and using the QMC5883 output so if you get the I2C communication down, everything should will stay the same.
