### ISSUE TITLE
mgPerDigit

### ISSUE THREAD

**Issue by zfranco55** [mprograms/QMC5883LCompass#10]
compared to other libraries (for HMC5883) not found the normalization function with respect to offset and gain, or am I doing something wrong?

**Comment by mprograms** [comment]
By gain I assume you mean sensitivity. This is controlled on the chip by the function `compass.setMode(MODE, ODR, RNG, OSR)`. See readme.md for more info.

Offset is a feature that I have planned to add but I have not had time. For right now, the best solution is to hard code your offset value and add it to the azimuth value before it is used. For example:

```
int offset = -5;

. . .

a = compass.getAzimuth();
a+= offset;
```
