### ISSUE TITLE
GetAzimuth does not change with, and can not get my magnetic heading.

### ISSUE THREAD

**Issue by radding** [mprograms/QMC5883LCompass#19]
Hello, I am looking to build a prototype for an autopilot for a boat. I am using the knock off gy-271 and this library to get the magenetic heading of the boat, in degrees (for example heading 176 degrees) so that I can plug in my actual heading to the PID controller to steer towards my desired heading.

The problem I have is that every time I call `compass.getAzimuth()`, it returns a consitent value, no mater what direction I point the chip in. The value does change based on the calibration settings of the compass. For example, with this calibration: `[[-19061,23237],[416,27639],[-3631,432]]` the chip returns 280. I have tried to change the smoothing, mode and read the documenation, but I can not figure out what I am doing wrong. Here is the code I am writing: https://github.com/radding/Autopilot. Specifically, here is where I am setting up the compass: https://github.com/radding/Autopilot/blob/main/microcontroller/microcontroller.ino#L57. 

I have the chip upright, and SDA is connected to PIN A4, and SCL is connected to pin A5 on my arduino uno. Any pointers would be appreciated!

**Comment by mprograms** [comment]
I believe the GY-271 is of the HMC5883L chipset. In this case, this library will not work for your needs. Many online retailers use HMC5883L and QMC5883L interchangeably but they are not the same. They use different registers. You will need to find a library that supports the HMC5883L chip or purchase a QMC5883L chip.
