### ISSUE TITLE
Wemos D1 Mini usage

### ISSUE THREAD

**Issue by BluePython339** [mprograms/QMC5883LCompass#6]
Hey, i have this chip and would like to use it in combination with my wemos d1 mini, i used the pinout d1 -> scl d2 -> sda and 5v and gnd but i'm not getting any output at all except for 0's. any idea?

**Comment by TheNitek** [comment]
Did you try 3.3V? Maybe you mixed up d1 and d2? Wiring sounds fine otherwise.
