### ISSUE TITLE
In which unit are the x, y, z values?

### ISSUE THREAD

**Issue by StefanBoehnert** [mprograms/QMC5883LCompass#8]
See caption

**Comment by alidastgheib** [comment]
Hi Stefan,

The following two images are taken from the QMC5883 datasheet:

![img-1](https://user-images.githubusercontent.com/34123287/102850492-de147880-442e-11eb-88e9-4b9d73612321.jpg)

![img-2](https://user-images.githubusercontent.com/34123287/102850525-eff61b80-442e-11eb-9f59-40160ab0d9c2.jpg)

--------------------------------------
Now, let's assume you have programmed "Dynamic Output Field Range" to be `+-2G`. 
And, let's assume the 16-bit output for "x axis" is `-1204`.
The "B field" (magnetic field) for that axis would be: 
(-1024/32768) * 2000 = -62.5 mG [milli Gauss]
--------------------------------------

To program the "Dynamic Output Field Range" for `+-2G`, write 0x00 in RNG control register; or:
Simply call `compass.setMode(MODE, ODR, RNG, OSR);` after you have called `compass.init();`.
